### ISSUE TITLE
Any plans to publish to NPM?

### ISSUE THREAD

**Issue by markehost** [jonathantneal/postcss-number-functions#1]
Hi Jonathan, great work work filling this need in postcss.  Was wondering if you had any plans to publish this package to the NPM registry? 

Thanks!

**Comment by BerkeleyTrue** [comment]
ping @jonathantneal

**Comment by jonathantneal** [comment]
I haven’t published this because the math doesn’t resolve as expected. It resolves completely linearly, while normally (in JS, at least) math resolves multiplication and division before addition and subtraction.

**Comment by romainmenke** [comment]
CSS has progressed a lot in the last ±7 years and we now have native support for these functions.

There is also a JS package to emulate the native math functions: https://github.com/csstools/postcss-plugins/tree/main/packages/css-calc
